// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: PRJ_VERDE

#include "ui.h"
#include <WiFi.h>
lv_obj_t *wifiStatus;
lv_obj_t *ssidLabel;
void ui_Screen1_screen_init(void)
{
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_fundoverde_png, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Container1 = lv_obj_create(ui_Screen1);
  lv_obj_remove_style_all(ui_Container1);
  lv_obj_set_width(ui_Container1, 480);
  lv_obj_set_height(ui_Container1, 20);
  lv_obj_set_x(ui_Container1, 0);
  lv_obj_set_y(ui_Container1, -230);
  lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  // O SINAL A REDE

  wifiStatus = lv_label_create(ui_Container1);
  lv_obj_set_width(wifiStatus, LV_SIZE_CONTENT);   
  lv_obj_set_height(wifiStatus, LV_SIZE_CONTENT);  
  lv_obj_set_align(wifiStatus, LV_ALIGN_LEFT_MID);

  ssidLabel = lv_label_create(ui_Container1);
  lv_obj_set_width(ssidLabel, LV_SIZE_CONTENT);   
  lv_obj_set_height(ssidLabel, LV_SIZE_CONTENT);  
  lv_obj_set_x(ssidLabel, -167);
  lv_obj_set_y(ssidLabel, -1);
  lv_obj_set_align(ssidLabel, LV_ALIGN_CENTER);
 
  if (WiFi.status() != WL_CONNECTED)
  {
    lv_label_set_text(ssidLabel, "SEM WI-FI");
    lv_label_set_text(wifiStatus, LV_SYMBOL_WARNING); /*Set the labels text*/
  }
  else
  {
    lv_label_set_text(wifiStatus, LV_SYMBOL_WIFI);     /*Set the labels text*/
    lv_label_set_text(ssidLabel, WiFi.SSID().c_str()); /*Set the labels text*/
  }

  lv_obj_set_style_text_color(wifiStatus, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(wifiStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_text_color(ssidLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ssidLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  Serial.println("Tela principal (ui_Screen1) criada.");
}
