// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: PRJ_01
#include <Arduino.h>
#include "ui.h"
void botaoclicado(lv_event_t * e)
{
	Serial.println("Botão ClicKed");
}
